version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    command: --authentication_policy=mysql_native_password --init-file=/tmp/createdb.sql
    ports:
      - 3306:3306
    volumes:
      - "./src/db/createdb.sql:/tmp/createdb.sql"
      - mysql-data:/var/lib/mysql
    container_name: 'notetaker-db'
    environment:
      - MYSQL_ROOT_PASSWORD=root@1234
    networks:
      - notetaker-net
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis-data:/data
    container_name: 'notetaker-redis'
    networks:
      - notetaker-net
  notetaker-backend:
    build:
      context: .
    image: notetaker-backend:latest
    container_name: notetaker-backend
    depends_on:
      - mysql
      - redis

    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - '3000:3000'
    networks:
      - notetaker-net
networks:
  notetaker-net:
volumes:
    mysql-data:
    redis-data: